services:
  api:
    image: api:latest
    hostname: api
    networks:
      api-network:
    ports:
      - "8080:8080"
    environment:
      PG_HOSTNAME: postgres
      PG_PORT: "5432"
      PG_DATABASE: "atlas"
      PG_USERNAME: "api"
      PG_PASSWORD: "api"

  postgres:
    image: postgres:17.2
    hostname: postgres
    networks:
      api-network:
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /data/postgres
    volumes:
      - postgres-data:/data/postgres
      - ./postgres/postgresql.conf:/etc/postgresql/postgresql.conf
      - ./postgres/pg_hba.conf:/etc/postgresql/pg_hba.conf
      - ./postgres/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh

volumes:
  postgres-data:
networks:
  api-network:
    external: true